export const COM_SHOW_TOAST = 'COM_SHOW_TOAST'
export const COM_SHOW_SUCCESS = 'COM_SHOW_SUCCESS'
export const COM_SHOW_FAIL = 'COM_SHOW_FAIL'
export const COM_TOAST_MSG = 'COM_TOAST_MSG'
export const COM_SHOW_ALERT = 'COM_SHOW_ALERT'
export const COM_ALERT_MSG = 'COM_ALERT_MSG'
export const COM_LOADING_STATUS = 'COM_LOADING_STATUS'

export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS'
